jwt:
  secret: lkfasdjflkasjdlfasikfjlasdkfjaslfkajsdsalfdkjasdlfkjgdfsgsfdgsdfgsdfgsdfgsdfgsdfgsdfgsfdgdsfgsdfgsdgsdfgsdfg
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
  jpa:
    hibernate:
      ddl:auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG